apiVersion: v1
kind: Service
metadata:
  name: login-backend
  namespace: default
spec:
  type: ClusterIP
  selector: { app: login-backend }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
