apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-frontend
  labels:
    app: login-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-frontend
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: login-frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: frontend
          image: ghcr.io/${REPO_LC}:{{GIT_SHA}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 2"]
