apiVersion: v1
kind: Service
metadata:
  name: login-frontend
  namespace: default
spec:
  type: ClusterIP
  selector: { app: login-frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
